### ISSUE TITLE
This is cool!

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#1]
I'm about to post various other issues and suggestions, but before I did so, I just wanted to say this is a cool project.  I'd been tempted to do this sort of thing myself, when I stumbled across yours.  I appreciated how you did this with AST's, which was much better than the wheel-reinventing approach I'd considered using.  So rather than start fresh, I'll work from your very useful starting point, and share the results with you (and whomever else is interested).  Thanks for the awesome work, and for sharing it with others.  If the other issues I post seem negative, please remember these positive notes here!

**Comment by Lonami** [comment]
This is a wonderful thing to wake up to, thanks!
