### ISSUE TITLE
Automatically copy compiler output to clipboard?

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#10]
(Mostly posting this to have a reminder of it.)  It'd be nice if we could set it up so that compiling a file/function automatically copies  the compiler output to the clipboard, to save a couple steps in the process before clicking over to Mindustry and installing the compiled program from the clipboard into a processor.

It looks like Python's tkinter module would be able to do this, and is bundled with many Python installations, so usually would not be an additional dependency.

**Comment by Lonami** [comment]
I believe tkinter is not installed by default? Maybe it's a thing in some distros, but definitely (just tried) is a thing in Termux (Android terminal emulator).
