### ISSUE TITLE
How will Pyndyustric interact with Mindustry mods?

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#11]
Some Mindustry mods add new resources, new blocks and/or new units.  I haven't tested to see how well mlog itself behaves with such new content.  E.g., if a mod adds snowballs as a resource, can mlog sensors then detect @snowballs in a container?  Assuming modders have jumped through whatever hoops they need to to get mlog to handle their modded content, are there even further hoops we'd need people to jump through to get Pyndustric to handle the modded content too?

A minor worry is that stuff we set up for linters won't recognize modded content, so the linter would probably flag things like 'snowballs' as an undefined variable, which isn't that big of a deal.

It would be a bigger deal if (as I think the current Sensor code is implemented) Pyndustric simply refuses to treat snowballs as a resource, so refuses to let Pyndustric programs try to detect the amount of snowballs in a container (or refuses to let you bind modded units, or refuses to let you control modded buildings).  

To accommodate this, we may want to use more of a "duck-typing" approach than we currently do, so e.g., if someone types `container1.snowballs` maybe we should go ahead and compile that to try to sense @snowballs in container1, even if we had no idea that snowballs might be a resource?  Alternatively, perhaps we should allow a straightforward means for users to explicitly declare modded content, e.g., with something like `snowballs = Resource()` or `cattlebruiser = UnitType()`.

**Comment by Lonami** [comment]
As long as mods don't add new instructions, I think we're in the clear. For any pyndustric function that gives you a resource for example, there could be a generic one where you just specify the name.

**Comment by TelosTelos** [comment]
My understanding of your compiler is that if someone's program said `Sensor.snowballs(vault1)` you'd try to look up 'snowballs' in the RES_MAP you made, fail to find such an entry there, and therefore raise ERR_UNSUPPORTED_SYSCALL.

**Comment by TelosTelos** [comment]
I'm leaning in the direction of compiling every attribute reference of the form `object.attribute` that we don't recognize into a mlog sensor reading like `sensor object @attribute`, perhaps outputting a warning that we had done so.  That would make Pyndustric automatically compatible with mods that add attributes (like new resource types) and also automatically forwards-compatible with future versions of Mindustry that add new sensor-able `@attributes`.

Similarly, I'm leaning towards compiling any instance of `Unit.bind_next( unittype )` as `ubind unittype` regardless of whether we recognize the given `unittype` or not, perhaps again producing a warning if we don't recognize it, which again would make this automatically compatible with mods and/or future Mindustry changes/additions of unit names.

(My runner-up alternative is to have users predeclare unknown elements, e.g., with `cattlebruiser = UnitType()` or `snowballs = Resource()` either within the compilable function as a no-op command, or preceding it.  But I doubt we could count on users always doing this right.)

We don't yet have a good "warning" mechanism.  Left to my own devices, I'd probably jerry-rig something simple, like printing the warning to console perhaps with a flag to suppress the warnings, but you might have a more standardized preference?

**Comment by Lonami** [comment]
I'm okay with the approach you describe in the first two paragraphs, but beware `object.attributes` breaks if either name contains hyphens (think `blast-drill`, which needs to be converted to `blast_drill`). Reinterpreting every underscore as hyphen is also not an option, because there may be objects named with underscores (this isn't the case currently, but a mod could do that).

WRT warnings, I wouldn't bother for now. Maybe if it becomes a big issue we can track and implement the feature later.

**Comment by Lonami** [comment]
I'm going to close this since it's not really actionable currently.
