### ISSUE TITLE
Support multi-assignment like x = y = 0

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#22]
I thought an issue might have been created for this already, but I couldn't find it.

At any rate, just marking here that I've done this in my current version, lest I forget to mention it later.

**Comment by Lonami** [comment]
I left a comment for this at https://github.com/Lonami/pyndustric/issues/2#issuecomment-757454702, but there's no harm in tracking it here.

**Comment by Lonami** [comment]
Implemented in https://github.com/Lonami/pyndustric/commit/125037cf1a63d81cf9b7b913e1a309a7d9437dc4.
