### ISSUE TITLE
Should Env.attributes really be treated as methods?

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#25]
The analogs of these in mlog are treated as variables, which match up more closely to python attributes than to callable methods.  Presenting these as methods also gives the misleading impression that these might require multiple instructions, when most (all?) uses of these are actually going to be incorporated into the same op that uses them, so won't add to instruction count at all.

Some of these also should probably be made to work on their own without an `Env.` prefix.  E.g., I've been using `Unit` for `@Unit` and would probably do the same for at least `@this` --> `This`.

I guess I'm tempted to do away with `Env` entirely, and just use some sort of capitalized variables for all of these variables, staying closely parallel to how mlog does it, replacing `@` with capitalization.  If we're worried about this colliding with user-defined variables, we can make sure to declare these in .pyi to help make them appear special in editors with mouseover documentation, and we probably should raise compiler errors if they attempt to assign to a reserved variable, to help set people on the right path.

**Comment by Lonami** [comment]
They're methods to signal that they're somewhat special and may be doing something non-standard behind the scenes, or can change between invocations. But properties does make it cleaner.

> we probably should raise compiler errors if they attempt to assign to a reserved variable

Power users may actually want to read or write to compiler variables for some fancy tricks. Maybe if it's compiled with `--sudo` or something we allow that use?

**Comment by TelosTelos** [comment]
By "reserved variables" I meant things like Unit or This (and whatever other current Env.attributes we decide to treat as simple variables, perhaps all of them).  If we interpret these in any ast "load context" as meaning their mlog `@equivalent`, then I don't see what sort of fancy tricks a power user could use storing values to them (e.g. with `Unit = 3`), since mlog won't allow us to override their mlog `@equivalents`, and if we overwrite the variable name itself in mlog (e.g. with `set Unit 3`), the power user will have no way to ever read that new value, since the read command will automatically be compiled to the @equivalent (@unit, in this example),  So that's why I was thinking we should raise a compiler error if they attempt 'Unit = 3'.  Am I missing something?

**Comment by Lonami** [comment]
Ah, by reserved variables I meant things like `__pyc_sp` for the stack pointer or `__pyc_ret`. Yeah it doesn't make much sense to let them assign to, say, `Unit` (unless they do `Unit = anotherunit` in which case it could mean bind?).

**Comment by Lonami** [comment]
Not needing to call `Env` attributes implemented by https://github.com/Lonami/pyndustric/commit/e7c14ee9a73141d7518fd8b68ee9751a416b6ec9. Arbitrary resources from the "environment" implemented by https://github.com/Lonami/pyndustric/commit/76161863ddb9d083dd914079033dc29c0c7e56b8 (e.g. `Env.copper`).
