### ISSUE TITLE
Use of subscripting?

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#29]
Just noting here that I've been thinking of allowing two uses for `object[ index ]`

`memoryblock[integer]` should be usable to read/write from the slot with that number in a memory block

`object['@sensableattribute']` should compile to a sensor command to read `@sensableattribute` in object.  We already allow most current/future sensable attributes via `object.sensableattribute` but this may not work for future attributes that contain underscores.  I also have yet to check whether mlog allows dynamic assignment of attribute type, e.g. as in the following pseudocode, but if it does, we'd need some syntax like this to have any hope of allowing it:

```python
res = @copper
amt = vault1[ res ]
```

**Comment by Lonami** [comment]
Probably easier to provide a method `read`, because subscripting is for sensing things, not reading. So we'll have:

```python
index = 7
memory1.read(index)

resource = Env.copper
container1[resource]
```
