### ISSUE TITLE
Treating blocks as objects

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#3]
Pyndustric allows use of sensors to interact with blocks, e.g., with `Sensor.copper(container1)`

For many Python coders, it would be more intuitive to write this as `container1.copper`.  It'd be nice to support this sort of object-oriented approach, in place of, or in addition to the more verbose Sensor option.

Similar usage may make sense for calling methods or changing attributes associated with objects, e.g. `reactor.enabled = False`.

**Comment by Lonami** [comment]
This would be super cool and how I originally envisioned such a thing. The current handling of expressions quickly got a bit messy since they can occur pretty much anywhere, so before implementing this, it might be worth cleaning it up.

With regards to type hinting, we'll likely want a class with these properties and maybe we can provide a builtin `link()` function that does nothing but would make linters happy, or add a class `Links`:

```python
class _Links:
    def __len__(self) -> ...
    def __getattr__(self, name) -> Link: ...
    def __getitem__(self, name: Union[int, str]) -> Link: ...

Links = _Links()
# user code
container1 = Links.container1
drill = Links['airblast-drill1']
for i in range(len(Links)):
    link = Link[i]
```

Of course `Links.name` is redundant as `name` alone works, but linters aren't happy with just `name`. Effectively, getattr/item are no-ops (but the compiler will need to associate the old name to the new one).

**Comment by TelosTelos** [comment]
I fear I didn't follow quite all of this.  I'd been playing with a superclass Block, which I think may be roughly equivalent to your _Links.  I then define MemoryBlock as a subclass, since, unlike most linkable Blocks, memory blocks support a sort of indexed operation, which I'd been thinking of offering ordinary Python indexing syntax for.  So I have a subclass definition like the following:
```python
class MemoryBlock(Block):
    def __getitem__(self, index): pass
    def __setitem__(self, index, value): pass
```
Of course none of these definitions actually need to be implemented, since the actual code will be run by Mindustry, not in Python -- all we need is enough to indicate to PyCharm / linters what role this will play.

Then in defining the compilable function, I have a no-op header like the following, which indicates that memory1 will be of type MemoryBlock, and hence PyCharm is happy letting me type things like memory1[1].

```python
def findPlayer(memory1: MemoryBlock):
   # ...snip...
    memory1[1] = unit
``` 
Similarly, other subclasses' dummy definitions would indicate which attributes and methods they would have, like .copper, .x or .enable().

I guess the main differences between this and what you suggested are (1) I was using function argument type annotation to specify types whereas you were using a no-op assignment to the variable name (both could work), and (2) I'd been imagining importing types like MemoryBlock into the global namespace, whereas you'd been thinking of accessing them as attributes of a Links object? (again both could work)

**Comment by Lonami** [comment]
The problem with (1) is that functions would now have a set of normal parameters and another of "magic" parameters. The problem with (2)'s "magic imports" is that type hinting those correctly could get tricky, so I think my idea of a "magic object" (as opposed to a "magic module") is more approachable. My suggestion is an object because `Links.name` is very comfortable to type out, but a builtin `link("name")` works too.

**Comment by TelosTelos** [comment]
I'm leaning in the direction of having there just be a single Block type for all linkable blocks, rather than trying to enforce on our end the fact that only certain blocks have certain attributes/methods.  So, on the approach I was suggesting the only annotation would come from optionally listing the linked blocks (like `container1` and `ripple1`) as arguments to the compilable function, and optionally adding `: Block` after each, to help linters make block-appropriate suggestions.  Both of these would be optional, with the main benefits of doing them just being to help the linter help you, and to help readers make easier sense of the code.  As for the body of the code itself, this would refer to blocks just as they are referred to in mlog, e.g., as `container1` without any need to preface with something like `Links.` or `link(` , and the linter will be happy with these since they were declared as function arguments. 

I.e., I'm suggesting something like the following:
```python
def ammo_feeder( container1 : Block, ripple1 : Block ):
  """This simple compilable function flags an unflagged flare and has it forever ferry ammo from container1 to ripple1."""
  while not (Unit and Unit.flag == 0):  
    Unit.bind_next(flare) # find a flare whose flag is 0
  Unit.flag = 1   # set its flag to 1, so other processors will know not to take control of it
  while Unit:  # so long as this unit survives...
    while dst( Unit - container1 ) > 5:
        Unit.move_to(container1)
    Unit.get_item(container1, graphite, 20)
    while dst( Unit - ripple1 ) > 5:
        Unit.move_to(ripple1)
    Unit.put_item(ripple1, graphite, 20)
```

**Comment by Lonami** [comment]
> I'm leaning in the direction of having there just be a single Block type for all linkable blocks, rather than trying to enforce on our end the fact that only certain blocks have certain attributes/methods

Sounds good to me, this will simplify things a lot as we now don't really need to track the types. It's up to the user to make sure a variable is a valid block (much like in mlog, and this is all duck typed anyway so…).

> as arguments to the compilable function

If I'm understanding you correctly, these arguments are "magic" and there won't actually be a function generated, just the function body. I'm not sure I like this, it means I can't do the following:

```python
def is_even(n):
    return n % 2 == 0

compile(is_even)
compile('''
x = is_even(7)
print(x)
''')
```

Maybe we have a `compile_body` that won't emit a mlog function, but rather the body? It's a bit weird, and:

```python
def main(container1: Block):
    ...
```

…isn't that much better than:

```python
container1: Block = link()
...
```

Aside: there's a mode known as "approach" which behaves like "move" but stays "dist" apart from the target.

**Comment by TelosTelos** [comment]
Yes, the thought is that `compile( ammo_feeder )` would generate an mlog program (a text-string, ideally automatically copied straight into the clipboard, so you can then alt-tab over to Mindustry and paste it straight into the device), so the initial `def ammo_feeder(...)` line would end up being no-op in the compiled version, and would instead serve only organizational/linting/understanability purposes.

Python allows nested function definitions within function definitions, so you can still define functions within your compilable program to have other parts of your compilable program call, and those inner functions will be compiled alongside the surrounding program, as you've already set up pyndustric to do.

```python
def program_to_compile( container1: Block ):

    def is_even( n ): return n%2 == 0  # this inner function will be compiled alongside the rest of this program

    print( is_even(container1.copper) ) # and the inner function can be called from other parts of the program
```

**Comment by TelosTelos** [comment]
You probably wouldn't want to first compile some functions and then compile some other code that makes reference to those compiled functions, since mlog jump commands depend on line-numbering, and once things are combined together, the line numbering will change for all but whichever function (if any) gets to go first (though it would be fairly straight-forward to substitute new line numbers into jump commands if you did want to concatenate two or more compiled programs).

**Comment by TelosTelos** [comment]
There would be something attractive about being able to define a helper-function once that will end up being used in multiple compilable programs, without needing to copy-paste a definition of that function into each of those other programs (the way the approach I sketched above would require, or your command-line approach that does one program per file would require).  Probably the way to do that is to have the visitor that visits the function-call somehow detect that this is a call to a function that is defined somewhere nearby, and automatically introspect that function's source code and splice it into what will be compiled.

Relatedly, it's quite tempting to set up _macro_ definitions that superficially look a lot like function definitions, but are compiled inline without any jumping, and with variable names changed appropriately to use a minimum of instructions.

**Comment by Lonami** [comment]
> automatically copied straight into the clipboard

Should this really be something the library should do? Users can trivially write something that loads, compiles and copies the program every second (effectively letting your editor's "save file" also "copy mlog to clipboard). I guess we could provide it though, since it isn't much code, as a separate utility file.

> Python allows nested function definitions within function definitions

Yes, but I originally avoided this because these functions actually capture their environment, and can be returned and passed around while the environment should be kept, which is quite a harder problem.

> and once things are combined together, the line numbering will change

The compiler could remember the old "line offset" and apply it on subsequent compilations.

> superficially look a lot like function definitions, but are compiled inline without any jumping

We could just provide a builtin `@inline` intrinsic decorator.

**Comment by TelosTelos** [comment]
I don't think I followed the bit about "Users can trivially write something that loads, compiles and copies the program every second (effectively letting your editor's "save file" also "copy mlog to clipboard)."  Why would anyone want to do this?  Wouldn't this basically break every other use of the clipboard to copy-paste other things?! 

The use I'd imagined was editing my compilable program in the pycharm editor, hitting Ctrl-S to save it, clicking down to the console, typing compile(fname), alt-tabbing to Mindustry, and pasting this compiled version of the program into a processor.   If compile() didn't automatically copy the compiled program into the clipboard, then I'd need to highlight a printout of the compiler's output and hit Ctrl-C to copy it to the clipboard before alt-tabbing to Mindustry, which would get old quick, especially if that output is hundreds of instructions long.   (IIRC, Mindustry also has a load-from-file option in addition to load-from-clipboard, so that could be an alternative use scenario, but even then, it'd be quicker to load the one thing in the clipboard than it would be to navigate a file-selection dialogue.)

---

Your decorator approach for defining macros is a lot cleaner than the best alternative I'd thought of.  I guess the AST will include a node for the decorator, rather than actually applying it?

**Comment by Lonami** [comment]
> Why would anyone want to do this? Wouldn't this basically break every other use of the clipboard to copy-paste other things?!

Well, yes, it would break any other clipboard use, but you would stop the program once you're done configuring your logic processors. And it could only update the keyboard if the file changes, not always.

> I guess the AST will include a node for the decorator, rather than actually applying it?

Of course, the AST is provided as-is, and no transformations are made or code ran:

```python
import ast
>>> print(ast.dump(ast.parse('@foo\ndef bar(): pass'), indent=4))
Module(
    body=[
        FunctionDef(
            name='bar',
            args=arguments(
                posonlyargs=[],
                args=[],
                kwonlyargs=[],
                kw_defaults=[],
                defaults=[]),
            body=[
                Pass()],
            decorator_list=[
                Name(id='foo', ctx=Load())])],
    type_ignores=[])
```

**Comment by TelosTelos** [comment]
I guess this conversation may have veered off topic (likely mea culpa), but back on topic, I'll note that my version now supports block.attr and unit.attr access for sensable attributes of blocks and units, and my nascent version of a .pyi module declares all currently known sensable attributes for these classes, to make linters help out with spelling these. 

As we discussed somewhere (???) else, this liberally interprets any unfamiliar expression of the form `object.attribute` as being an attempt to use mlog's `sensor` to read that attribute from that object, to allow compatibility with mods and future versions of mindustry that might include attributes we don't know about.  It converts names from python-style to mlog style by prepending `@` and replacing `_` with `-`.  You noted elsewhere that this might run into problems if someday someone creates a mindustry attribute that really is supposed to have an underscore.  I'm not sure the best way to handle that?

**Comment by Lonami** [comment]
Using a string such as `'@foo_bar'` to refer to a literal name.

**Comment by TelosTelos** [comment]
Strings can indeed include @'s and -'s but they can't take the place of `.attribute` in `block.attribute` notation, so we'd need a new syntax to allow strings.  

It would be fairly intuitive to also give these objects a lookup interface like a python dict, so `vault1["copper"]` would compile equivalently to `vault1.copper`, but the dictionary lookup notation can accept arbitrary strings.  I'd still want to keep the `object.attribute` notation too, since it's cleaner, more intuitive for object-oriented coders, and the linter will provide autocompletion hints for .attributes, but probably not for dictionary lookups.

**Comment by TelosTelos** [comment]
Do you know if mlog allows for something along the lines of this pseudocode, where a program dynamically specifies which resource its interested in?
```
c = @copper
sensor var block c
```
If so, we'll probably need something like dictionary lookup (or an implementation of something akin to `getattr()` ) to support this.

**Comment by Lonami** [comment]
The following program:

```
set c @copper
sensor result container1 c
print result
printflush message1
```

With a `container1` and `message1` linked, the message correctly prints the number of copper items in the container as I update. So I think mlog has support for variables to reference anything.

**Comment by Lonami** [comment]
I think we should treat anything as a map. The problem with attribute access is that we can't use strings for the attribute, but with item index we can, and it still lets us assign new values:

```python
x = container1[copper]
y = "custom_block"["custom_resource"]
```

This frees up the attributes for well known things we might want to change, like `enabled` or `shoot`, which for simplicity could just be methods:

```python
conveyor1.enabled(False)
dagger.shoot(10, 20)
```

**Comment by Lonami** [comment]
Along with https://github.com/Lonami/pyndustric/commit/7e1a49abf390c68513de998ca07d7798c4bb757c, this issue is fully fixed now.
