### ISSUE TITLE
Diverging forks

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#39]
This is more of a meta-issue, but for lack of a better idea of where to post it, I'll do so here.

@Lonami It's good to see you back active again.  

As I mentioned in another thread, I've done a lot of work implementing vectorization, and have it near working.  I have just a few remaining issues about using sensors to update vectors at the right time, auto type-detection for edge cases like never-assigned variables, and cleaning away clutter that ended up not being necessary.  Automatic type detection, vectorization, and a robust local/global system required reworking a _lot_ of the inner representation of Instructions and of variables/atoms, making the latter their own data-types organized in a class hierarchy, rather than just cramming them into big strings like our old code did.

As a consequence, any change you make to the old way of doing things, like the commits you recently made, will end up needing some work if it's going to be translated into the new Atom-based system.  That work may be tricky for you, at least until you figure out the new system.  For me, it'd generally be about as easy to do these small commits from scratch as it would be to try to convert from yours.

I'm not sure what the best solution to all this is.  It may be that you'll decide you aren't interested in taking on board all my reworked vectorized stuff, in which case we'll just end up with two separate forks.  Or it may be that one of us will end up reconciling the two together.  If that's the route we end up going, I think the easiest path, in the next few days, may be just for us to agree in the discussion about what the syntax should be, and have me incorporate that directly, rather than having our forks continue to diverge.  At any rate, when I post issues here, I'm usually thinking of them as decision points that you might want to have a say in, rather than tasks for you to do.  But of course you're welcome to do whatever you want...

**Comment by Lonami** [comment]
Unfortunately, our development process is far too different for it to be worth it for me to keep track of all the changes. Basically, the cost of implementing some feature from scratch on my own is likely to be a lot lower than scanning through your huge commits and picking up the relevant parts, adding them in smaller commits in my code.

*(Note: I'm not saying or implying that your development process is inherently bad, I'm simply pointing out that it's different from mine).*

At the moment, I have no plan to unify both forks again, but if you ever want to do that once this main repository is feature-complete enough, you're more than welcome to do so. So, I think it's fine for the forks to have diverged.

I'm going to close this issue since it's not tracking any particular bug, but feel free to keep posting comments or discuss it further.

**Comment by TelosTelos** [comment]
If at some point one of us wants to re-merge these, here are the main steps that would be involved in converting an instruction created your old way (like the ones in your recent updates) to one created my new way.

A typical old way of creating an instruction would prepare atoms for use as arguments in an instruction via `compiler.as_target()` and `compiler.as_value()`.  My current division of labor uses `as_variable()` to construe something as a variable (e.g. as a target for setting), and takes care to link multiple instances of the same variable together, which helps for type-tracking, local/global distinction, function substitutions, and vectorization.  My `as_Atom()` is the rough equivalent of the old `as_value`, generating an atomic way of referring to some AST-node, generating a dummy variable for it if necessary.  Since "Atoms" are the primary building blocks of Instructions in my new way of doing things, it makes more sense to call this "as_Atom".  As_atom ends up calling upon `as_variable` to deal with variables, to put a lot of common functionality into one place.  

A typical old way of creating an instruction concatenated its arguments together into an f-string using something like `f"command {arg1} {arg2} {arg3}"`.   In the new way of doing things, this would instead be `Command_Ins( arg1, arg2, arg3 )` where `Command_Ins` is defined in my mlog.py and includes information about number and types of arguments and vectorizability for this type of instruction.

For most run-of-the-mill practical purposes, those are the main things that have changed, though adding new Instruction types (e.g., I still haven't added Unit.commands) or adding new types of Atoms (e.g., if we follow up on our idea of allowing a Stack data-structure) would require delving into the details of how Instructions and Atoms are implemented.  That'd be straightforward for me to do (mostly just copying the closest existing analog and making relevant tweaks), but it would perhaps be more involved than you'd want to do.
