### ISSUE TITLE
Making PyCharm more helpful for Mindustry coding

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#4]
PyCharm can provide various helpful hints for coders, like word completion or highlighting undefined attributes of objects.  Since Pyndustric aims to bring some of the convenience of Python coding to mindustry logic programming, it would be nice if it could support this sort of convenience too.

As a first approximation, this would require creating dummy classes with attributes and methods corresponding to those that Pyndustric will support, importing these at the top of a to-be-compiled function, and using type annotations to indicate to PyCharm what classes various elements belong to.

**Comment by Lonami** [comment]
This is supposed to be [`pyndustri.pyi`](https://github.com/Lonami/pyndustric/blob/master/pyndustri.pyi)'s job, but I might have messed that up because I wrote it by hand (not auto-generated) and I haven't tested it.

**Comment by TelosTelos** [comment]
Ah good, I hadn't understood what pyndustry.pyi was for before, but it is indeed similar to what I'd had in mind.  I've been writing similar stuff for unit control, since you don't seem to have implemented much of that yet.  I guess the proper home for this might will be in pyndustry.pyi

How did you imagine people using pyndustry.pyi, when (I think) you can't have an import command in the file you'll compile without it generating an error?  Since I'm setting it up to compile individual functions, it then works fine to import this sort of dummy stuff prior to the function definition, and it also lets me do type annotation on (not-actually-used) function arguments indicating what blocks this logic block should be linked to, so that PyCharm knows what type to take them to be.

**Comment by Lonami** [comment]
`import *` is the only thing that's supported, since well, that's pretty much what happens when using pyndustric (everything is visible and should be imported, as if it was part of a "prelude"):

https://github.com/Lonami/pyndustric/blob/a9ced596da27948880ef184170bce236ddf0c3c9/test_all.py#L514

**Comment by Lonami** [comment]
Closing since [`pyndustri.pyi`](https://github.com/Lonami/pyndustric/blob/master/pyndustri.pyi) already exists. It might be incomplete but over time it should be filled in.
