### ISSUE TITLE
Can't set pyndustric up and running

### ISSUE THREAD

**Issue by Indieberrie** [Lonami/pyndustric#43]
When I try to run pyndustric as module (as stated in README.md), it says that there is no module named pyndustric.
When I try to install it as module, it gives me error of missing setup.py

**Comment by Lonami** [comment]
The idea is for you to put your code at the root of the repository like so:

```
root/
  pyndustric/
  yourcode.py
```

Then running `python -m pyndustric yourcode.py`. It's true it's a bit confusing so I'll leave this issue open to track that.

Please feel welcome to send a pull request improving either the `README` or adding a `setup.py` (or `pyproject.toml` or whatever is trendy nowadays)! I can label it as `hacktoberfest-accepted` if you're into that.

**Comment by Indieberrie** [comment]
Woah, your response was fast. I already made setup.py before opening this (because I needed to get it running, I didn't know it could be done the way you describe it, I'm adding it to pull request), but still wanted to open issue because I feel like it's a good practice. I'm kinda sad that I couldn't open pull request at the same time (I need id of issue to add to commit as "Fixes: id")
I'm not into hacktoberfest, but thank you
