### ISSUE TITLE
Supporting Interactive Console usage, and multiple mlog programs in one file

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#5]
Currently Pyndustric is configured to be used from the command line to operate on a file whose entirety (aside from comments) is the program that is to be compiled to mlog, or `compile` can be called with a string argument (though multi-line strings are a pain to get indented right in python).

For me, at least, the more intuitive approach would be to write each mindustry logic program as its own python function (or perhaps as its own class definition), potentially with multiple such functions in the same file, and then to compile these functions one at a time, or in a batch, e.g. from a Python interactive console with `compile(fname)`.

One advantage of this approach, related to issue #4, is that this would make it straight-forward to import relevant classes prior to code that is supposed to compiled, so that PyCharm would then be able to help with auto-completion and error detection.

This should be fairly straight-forward to implement, since Python allows for introspection of a function's source code, so if `compile` is passed a function as an argument, it can retrieve that function's source code and compile it.

**Comment by Lonami** [comment]
> though multi-line strings are a pain to get indented right in python

Heck yes they are, but at least [we have `textwrap`](https://github.com/Lonami/pyndustric/blob/a9ced596da27948880ef184170bce236ddf0c3c9/test_all.py#L141) (which costs runtime for writing a bit nicer code).

> since Python allows for introspection of a function's source code

Obvious remark: this will not work for native functiobs implemented in C, or if the source is otherwise not available.

But if `compile` would take `Union[module, function, str]`, that would be really nifty.

**Comment by TelosTelos** [comment]
Another reason I'm not a fan of writing compilable code as a string is that the IDE doesn't help with syntactic color-coding, auto-completion, linting, etc...

I'm having a hard time imagining a scenario where you'd ever want to compile any function that wasn't one you (or someone) had written specifically for Mindustry.  I guess there could be general-purpose helper functions (say an A* path-finding algorithm) that you'd like to include as part of your compilable Mindustry program.  But even in that case, you wouldn't just compile that function, you'd instead need to embed a copy of that function within compilable code that hooks it up to mlog API elements, and that seems to be pretty much the same regardless of whether what you're compiling is a (nested) function or an entire file.  So, anyway, yes you're right that not every Python function has introspectible source code, but that's compatible with supposing that things you'd want to compile into mlog could be written as Python functions that do have introspectible source code.   

(The biggest worry I have in this ballpark is that I'm not sure that functions that are defined in the console -- e.g. by highlighting the function definition in PyCharm and hitting the keyboard shortcut to evaluate in console --  end up with introspectible source code, which could trip up some possible uses.)

**Comment by TelosTelos** [comment]
Hrmm...  I've looked into this more, and now I'm not so sure about trying to define a function first in Python, then introspect its source, then compile that to mlog.  The most straightforward way to do it, using Python's inspect module, actually just is a roundabout way of going back to the source file and reading the function definition there, which we could have done easily enough manually.  It looks like the dill module could potentially work in a broader range of circumstances, e.g., for functions that get defined in the console, but I'm not sure that's really helpful enough to be worth the extra dependency.  Still I guess it wouldn't hurt to allow inspectable (i.e. defined in file) function arguments as an option for compile().

A big potential drawback of any approach that first evaluates a compilable function as Python is that it would lock us into making compilable functions be syntactically legit Python -- otherwise you couldn't even define the function in Python, much less introspect its source code afterwards.  Thus far we have been sticking to legit Python syntax, but (a) it's conceivable that we might want to adopt some other syntax for some operations, e.g., syntax that more closely matches mlog, and (b) it's possible that we might want to be able to run our compiler on buggy code that isn't quite legit to get helpful debugging info from the compiler.  (Or maybe having legit Python syntax is already a requirement for using AST, so this ship has already sailed???)

**Comment by Lonami** [comment]
> actually just is a roundabout way of going back to the source file and reading the function definition there, which we could have done easily enough manually

Yes :)

But to make this more useful, the `import`'s could actually become a "embed the imported file and evaluate it". Or something. It's also nice to be able to do `from foo import bar` and then compile `bar`, if you have a lot of utilities scattered around, or whatever.

> It looks like the dill module could potentially work in a broader range of circumstances

I'm a bit lost now, what would we use that for? From a quick look at the project, it seems to be a "better `pickle`" and I can't connect the dots.

> it would lock us into making compilable functions be syntactically legit Python

Well, that's the case now, `ast.parse` fails with a `SyntaxError` if the input is not valid Python.

> (a) it's conceivable that we might want to adopt some other syntax for some operations

No, I don't think so, pyndustric's goal is to compile Python into mlog, not a Python-like language. We can go really far with this, and I can't imagine anything that would require special syntax (for example, the jumps and labels can be function calls to be valid Python). We can even use more uncomon syntax like the `@` operator or slicing if we want to get fancy.

> (b) it's possible that we might want to be able to run our compiler on buggy code that isn't quite legit to get helpful debugging info from the compiler

That's `ast`'s job for syntax errors, and up to us to emit accurate semantic errors (e.g. "unsupported complex expression").

> Or maybe having legit Python syntax is already a requirement for using AST, so this ship has already sailed???

Ah heh you point this out at the end of your post. Yes, this ship's already sailed. But I think this is a good thing (after all, Python does the parsing for us, and the end result is that we can use actual Python).

**Comment by TelosTelos** [comment]
dill includes a method `dill.source.getsource` (and some related methods) that can be used to retrieve source code of functions.  Rather than needing to go read the function definition in a file, it can parse back through console history to find what code was used to define a function in an interactive console session.  This could be useful if someone wanted to compile a function they'd written in the console, or had evaluated directly from an editor without saving the edited file to disk.  I'm not sure that's a common enough use case for us to worry about though.  

Probably better to just use Python's built-in `inspect` module, and to warn users that compiling a function reads the most recently saved version of the file that contained the function's original source code, so they should save their edits to disk before compiling again, which seems fair enough, and would fit fine with the way that I personally use the interactive console.

**Comment by Lonami** [comment]
I'm going to close this. A REPL is currently out of the scope (but could be added in a PR if it's isolated enough from the rest of the code, so it's not too much of a burden to maintain). Compiling functions also is. My vision is a command-line tool but we can explore new things in a PR.
