### ISSUE TITLE
Support for illuminator color config and pack color

### ISSUE THREAD

**Issue by Leo-MathGuy** [Lonami/pyndustric#54]
Pack color is rgba[0-1] to a one color, used in config color for illuminators

**Comment by Lonami** [comment]
Could you provide a particular example on what you're trying to achieve? Do you have suggestions or ideas on what the pyndustric code could look like? I don't have enough experience with this myself to come up with a good design.

**Comment by Leo-MathGuy** [comment]
Uhh ok

colorA = colorPack(0,1,0.5,0.21)

illuminator1.config(colorA)

Screenshots soon

**Comment by Leo-MathGuy** [comment]
Sorry for the small delay,

Output:

https://github.com/Lonami/pyndustric/assets/86385005/1b3101fe-68ba-4f4c-95f4-033e1ff92716


Code for illuminators:

packcolor var r g b a
var - name of output variable
r     - red value
g    - green value
b    - blue value
a    - alpha, used in canvases

Output colors are "packed" with %rrggbb (hex format)


control color block 0 0 0:
block - illuminator

`packcolor red 1 0 0 1
packcolor brown 1 1 0 1
packcolor cyan 0 1 1 1
packcolor white 1 1 1 1
control color illuminator1 red 0 0 0
wait 0.4
control color illuminator1 brown 0 0 0
wait 0.4
control color illuminator1 cyan 0 0 0
wait 0.4
control color illuminator1 white 0 0 0
wait 0.4
`

**Comment by Leo-MathGuy** [comment]
Partially fixed by https://github.com/Lonami/pyndustric/pull/57

**Comment by Lonami** [comment]
Can this be closed since the above was merged or do you want to keep it open to track more progress?

**Comment by Leo-MathGuy** [comment]
Ok
