### ISSUE TITLE
Unit binding

### ISSUE THREAD

**Issue by TelosTelos** [Lonami/pyndustric#8]
It looks like you haven't implemented unit binding and control yet?  I've been fiddling with implementing this, and here will focus just upon how to do unit binding, which in mlog is done with a command like `ubind flare`.  I can imagine several syntaxes that could be used for this in Python.

```ubind( flare )```
This is a simple Python analog, though if we want linters not to complain, and if we want PyCharm to help with auto-completion and spell/type-checking, we'll need to import all the unit types into the global namespace.  This makes helpful documentation for ubind easily available to coders in an IDE like PyCharm.

```ubind( UnitType.flare )```
This is wordier, and further from pure mlog, but would put less in the global namespace, and might offer more relevant autocompletion hints.

```ubind.flare```
This is very close to mlog, doesn't clutter the namespace at all, and it would offer nice autocompletion.  But this may not offer as easy of documentation, and doesn't really look like a function call.

```ubind.flare()```  
This does look like a function call, but the empty parens are also kind of annoying.

```unit = ubind.flare  # or there can be unit = ... variants of any of the above```
This helps to make more clear that the role ubind plays is to change the referent of 'unit'.  

```unit = next( flare )```
This might be the clearest way of indicating to a Python coder the role that ubind actually plays in mlog programming, as a sort of iterator that yields successive units of the given type, and to make clear that subsequent references to unit will refer to the most recently iterated flare.  For linters, this would require that all unit types be put into the global namespace.

I'm tentatively leaning towards the last option, though probably making `next( flare )` be an equivalent abbreviation, and allowing `next( flare )` to work as an expression in longer lines of code, which is equivalent to first doing `ubind flare`, and then using `@unit` in that longer line, so e.g.,  flare1 = next( flare ) would work as a way of making `flare1` be a lasting reference to that flare.

**Comment by Lonami** [comment]
I was thinking we have a global `Unit` rather than doing something like `unit = …`, because we can only bind to one unit at a time. It is definitely more awkward to use though, but maybe it could just be `Unit.bind_alpha()` (and a `bind_` for each type).

**Comment by TelosTelos** [comment]
Hrmmm...  I'd been using `Unit` as a class to contain information about units, and `unit` as the Python equivalent of Mindustry's `@unit`, but maybe it would be better to use the capitalization to indicate that there's something special/unusual about this particular variable, and to come up with some other name for the class.  I do like how making .bind be a method of unit/Unit helps to convey that this will have an impact on Unit.  I'm now vacillating between `Unit.bind(alpha)` and `Unit.bind_next(alpha)`.

**Comment by Lonami** [comment]
Either naming is fine, perhaps `bind_next` which makes it clear it can only bind to one at a time if there's many.
